=== Sergio7DAW/LMSGI_U4/Actividad4_7/editorial.dtd
<!ELEMENT editorialBD (documento*)>  
<!ELEMENT documento (head, body)> 
<!ELEMENT head (title, subtitle)> 
<!ELEMENT title (#PCDATA)> 
<!ELEMENT subtitle (#PCDATA)> 
<!ELEMENT body (rNorte, rCentro, rSur)> 
<!ELEMENT rNorte (trimestre+)> 
<!ELEMENT rCentro (trimestre+)> 
<!ELEMENT rSur (trimestre+)> 
<!ELEMENT trimestre (librosVentas+)> 
<!ATTLIST trimestre valor (1|2|3|4) #REQUIRED> 
<!ELEMENT librosVentas (#PCDATA)>

=== Sergio7DAW/LMSGI_U4/Actividad4_7/editorial.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE editorialBD SYSTEM "editorial.dtd">
<editorialBD>
<documento>
  <head>
    <title></title>
    <subtitle></subtitle>
  </head>
  <body>
    <rNorte>
      <trimestre valor="1">
        <librosVentas></librosVentas>
      </trimestre>
      <trimestre valor="1">
        <librosVentas></librosVentas>
      </trimestre>
    </rNorte>
    <rCentro>
      <trimestre valor="1">
        <librosVentas></librosVentas>
      </trimestre>
      <trimestre valor="1">
        <librosVentas></librosVentas>
      </trimestre>
      <trimestre valor="1">
        <librosVentas></librosVentas>
      </trimestre>
    </rCentro>
    <rSur>
      <trimestre valor="1">
        <librosVentas></librosVentas>
      </trimestre>
      <trimestre valor="1">
        <librosVentas></librosVentas>
      </trimestre>
    </rSur>
  </body>
</documento>
</editorialBD>
