=== Sergio7DAW/LMSGI_U4/Actividad4_5/alumno.dtd
<!ELEMENT alumnoBD (alumnos*)>  
    <!ELEMENT alumnos (alumno)> 
    <!ELEMENT alumno (nombre, observaciones?, nif, resultado, ip?, mac?)> 
    <!ELEMENT nombre (#PCDATA)> 
    <!ELEMENT observaciones (#PCDATA)> 
    <!ELEMENT nif (#PCDATA)>  
    <!ELEMENT resultado (#PCDATA)>  
    <!ATTLIST resultado  estado (apto | noApto) #REQUIRED>
    <!ELEMENT ip (#PCDATA)> 
    <!ELEMENT mac (#PCDATA)>

=== Sergio7DAW/LMSGI_U4/Actividad4_5/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnoBD SYSTEM "alumno.dtd">
<alumnoBD>
  <alumnos>
    <alumno>
      <nombre></nombre>
      <observaciones></observaciones>
      <nif></nif>
      <resultado estado="apto"></resultado>
      <mac></mac>
    </alumno>
  </alumnos>
</alumnoBD>
