=== Sergio7DAW/LMSGI_U4/Actividad4_4/BDgestoriaSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" xml:lang="es">
    <xs:element name="BDgestoria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gestoria" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sedeCodigo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="cliente" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="descCliente" type="xs:string"></xs:element>
                                                    <xs:element name="numero " type="xs:string"></xs:element>
                                                    <xs:element name="vivienda" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                 <xs:element name="coste" type="xs:string"></xs:element>
                                                                 <xs:element name="resumen" type="xs:string"></xs:element>
                                                                 <xs:element name="plazo" type="xs:string"></xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="ID" type="xs:ID" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="empleadoAlta" type="xs:string"></xs:element>
                                                    <xs:element name="fechaAlta" type="xs:string"></xs:element>
                                                </xs:sequence>
                                              <xs:attribute name="codigo" type="xs:ID" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Sergio7DAW/LMSGI_U4/Actividad4_4/gestoria2.xml
<?xml version="1.0" encoding="UTF-8"?>
<BDgestoria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="BDgestoriaSchema.xsd">
  <gestoria>
    <sedeCodigo>
        <cliente codigo="x23-v53">
            <descCliente></descCliente>
            <numero></numero>
            <vivienda ID="a34-k345-l35">
                <coste></coste>
                <resumen></resumen>
                <plazo></plazo>
            </vivienda>
            <empleadoAlta></empleadoAlta>
            <fechaAlta></fechaAlta>
        </cliente>
    </sedeCodigo>
  </gestoria>  
</BDgestoria>
