=== Sergio7DAW/LMSGI_U4/Actividad4_4/biblioteca.dtd
<!ELEMENT bibliotecaBD (biblioteca*)>  
    <!ELEMENT biblioteca (cuidadCodigo)> 
    <!ELEMENT cuidadCodigo (cliente)> 
    <!ELEMENT cliente (clientePerfil, telefono, libro, empleadoAlta, fechaAlta)> 
    <!ATTLIST cliente codigo CDATA #REQUIRED>
    <!ELEMENT clientePerfil (#PCDATA)> 
    <!ELEMENT telefono (#PCDATA)>  
    <!ELEMENT libro (nombre, autor, plazo)> 
    <!ATTLIST libro ID CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA)> 
    <!ELEMENT autor (#PCDATA)> 
    <!ELEMENT plazo (#PCDATA)>
    <!ELEMENT empleadoAlta (#PCDATA)> 
    <!ELEMENT fechaAlta (#PCDATA)>

=== Sergio7DAW/LMSGI_U4/Actividad4_4/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bibliotecaBD SYSTEM "biblioteca.dtd">
<bibliotecaBD>
  <biblioteca>
    <cuidadCodigo>
        <cliente codigo="">
            <clientePerfil></clientePerfil>
            <telefono></telefono>
            <libro ID="">
                <nombre></nombre>
                <autor></autor>
                <plazo></plazo>
            </libro>
            <empleadoAlta></empleadoAlta>
            <fechaAlta></fechaAlta>
        </cliente>
    </cuidadCodigo>
  </biblioteca>  
</bibliotecaBD>
