=== Sergio7DAW/LMSGI_U4/Actividad4_4/gestoria.dtd
<!ELEMENT gestoriaBD (gestoria*)>  
    <!ELEMENT gestoria (sedeCodigo)> 
    <!ELEMENT sedeCodigo (cliente)> 
    <!ELEMENT cliente (descCliente, numero, vivienda, empleadoAlta, fechaAlta)> 
    <!ATTLIST cliente codigo CDATA #REQUIRED>
    <!ELEMENT descCliente (#PCDATA)> 
    <!ELEMENT numero (#PCDATA)>  
    <!ELEMENT vivienda (coste, resumen, plazo)> 
    <!ATTLIST vivienda ID CDATA #REQUIRED>
    <!ELEMENT coste (#PCDATA)> 
    <!ELEMENT resumen (#PCDATA)> 
    <!ELEMENT plazo (#PCDATA)>
    <!ELEMENT empleadoAlta (#PCDATA)> 
    <!ELEMENT fechaAlta (#PCDATA)>

=== Sergio7DAW/LMSGI_U4/Actividad4_4/gestoria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gestoriaBD SYSTEM "gestoria.dtd">
<gestoriaBD>
  <gestoria>
    <sedeCodigo>
        <cliente codigo="">
            <descCliente></descCliente>
            <numero></numero>
            <vivienda ID="">
                <coste></coste>
                <resumen></resumen>
                <plazo></plazo>
            </vivienda>
            <empleadoAlta></empleadoAlta>
            <fechaAlta></fechaAlta>
        </cliente>
    </sedeCodigo>
  </gestoria>  
</gestoriaBD>
