=== Sergio7DAW/LMSGI_U4/Actividad4_6/BDmodulosSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" xml:lang="es">
    <xs:element name="BDmodulo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="modulos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="modulo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombreMod" type="xs:string"></xs:element>
                                        <xs:element name="uds">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="ud">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                    <xs:element name="nombre" type="xs:string"></xs:element>
                                                                    <xs:element name="descripcion" type="xs:string"></xs:element>
                                                                    <xs:element name="tipo" type="xs:string"></xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>


<!-- <xs:element name="nombre" type="xs:string"></xs:element> -->

=== Sergio7DAW/LMSGI_U4/Actividad4_6/modulos2.xml
<?xml version="1.0" encoding="UTF-8"?>
<BDmodulo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="BDmodulosSchema.xsd">
    <modulos>
    <modulo>
      <nombreMod></nombreMod>
      <uds>
        <ud>
          <nombre></nombre>
          <descripcion></descripcion>
          <tipo></tipo>
        </ud>
      </uds>
    </modulo>
  </modulos>
   
</BDmodulo>
