=== Sergio7DAW/LMSGI_U4/Actividad4_6/modulos.dtd
<!ELEMENT modulosBD (modulos*)>  
    <!ELEMENT modulos (modulo)> 
    <!ELEMENT modulo (nombreMod, uds)> 
    <!ELEMENT nombreMod (#PCDATA)> 
    <!ELEMENT uds (ud)> 
    <!ELEMENT nombre (#PCDATA)> 
    <!ELEMENT ud (nombre, descripcion, tipo)> 
    <!ELEMENT descripcion (#PCDATA)> 
    <!ELEMENT tipo (#PCDATA)>

=== Sergio7DAW/LMSGI_U4/Actividad4_6/modulos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modulosBD SYSTEM "modulos.dtd">
<modulosBD>
  <modulos>
    <modulo>
      <nombreMod></nombreMod>
      <uds>
        <ud>
          <nombre></nombre>
          <descripcion></descripcion>
          <tipo></tipo>
        </ud>
      </uds>
    </modulo>
  </modulos>
</modulosBD>
