=== Sergio7DAW/LMSGI_U4/Actividad4_3/BDcochesSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" xml:lang="es">
    <xs:element name="BDcoches">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="coche" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="codigo" type="xs:string"></xs:element>
                            <xs:element name="marca">
                             <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="id" type="xs:ID" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>   
                            <xs:element name="modelo" type="xs:string"></xs:element>
                            <xs:element name="matricula" type="xs:string"></xs:element>
                            <xs:element name="potencia" type="xs:string"></xs:element>
                            <xs:element name="plazas" type="xs:string"></xs:element>
                            <xs:element name="num_puertas" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Sergio7DAW/LMSGI_U4/Actividad4_3/coches.xml
<?xml version="1.0" encoding="UTF-8"?>
<BDcoches xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="BDcochesSchema.xsd">

    <coche>
        <codigo>G7A9B2</codigo>
        <marca id="uno">Subaru</marca>
        <modelo>Impreza WRX STI</modelo>
        <matricula>XYZ1234</matricula>
        <potencia>300</potencia>
        <plazas>5</plazas>
        <num_puertas>4</num_puertas>
    </coche>

    <coche>
        <codigo>H9B3C5</codigo>
        <marca id="dos">Toyota</marca>
        <modelo>Celica GT-Four</modelo>
        <matricula>ABC5678</matricula>
        <potencia>250</potencia>
        <plazas>4</plazas>
        <num_puertas>3</num_puertas>
    </coche>

    <coche>
        <codigo>J8L1M9</codigo>
        <marca id="tres">Mitsubishi</marca>
        <modelo>Lancer Evolution IX</modelo>
        <matricula>LMN9876</matricula>
        <potencia>280</potencia>
        <plazas>5</plazas>
        <num_puertas>4</num_puertas>
    </coche>

    <coche>
        <codigo>P2F6R8</codigo>
        <marca id="cuatro">Nissan</marca>
        <modelo>Skyline GT-R</modelo>
        <matricula>DEF4321</matricula>
        <potencia>280</potencia>
        <plazas>4</plazas>
        <num_puertas>2</num_puertas>
    </coche>

    <coche>
        <codigo>Q7B4S3</codigo>
        <marca id="cinco">Honda</marca>
        <modelo>Civic Type R</modelo>
        <matricula>JKL1234</matricula>
        <potencia>306</potencia>
        <plazas>5</plazas>
        <num_puertas>4</num_puertas>
    </coche>

    <coche>
        <codigo>K9J2T5</codigo>
        <marca id="seis">Mazda</marca>
        <modelo>RX-7</modelo>
        <matricula>GHJ8765</matricula>
        <potencia>276</potencia>
        <plazas>2</plazas>
        <num_puertas>2</num_puertas>
    </coche>

</BDcoches>
